version: '2'
services:
    puffpdx-app:
        image: puffpdx
        external_links:
            - puffpdx-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/puffpdx
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    puffpdx-postgresql:
        extends:
            file: postgresql.yml
            service: puffpdx-postgresql
